# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Auth0Beta < Formula
  desc "Build, manage and test your Auth0 integrations from the command line"
  homepage "https://auth0.github.io/auth0-cli"
  version "1.33.0-beta.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/auth0/auth0-cli/releases/download/v1.33.0-beta.0/auth0-cli_1.33.0-beta.0_Darwin_x86_64.tar.gz"
      sha256 "50cb5a198ac64c595470b107c9e3b3cca1eb5b1baa866a11b4611da7f26941dc"

      def install
        bin.install "auth0"

        (bash_completion/"auth0").write `#{bin}/auth0 completion bash`
        (fish_completion/"auth0.fish").write `#{bin}/auth0 completion fish`
        (zsh_completion/"_auth0").write `#{bin}/auth0 completion zsh`
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/auth0/auth0-cli/releases/download/v1.33.0-beta.0/auth0-cli_1.33.0-beta.0_Darwin_arm64.tar.gz"
      sha256 "235208d548f8501c82977307c4d0a99191db0cb2e2512f3952cac59545cfaa78"

      def install
        bin.install "auth0"

        (bash_completion/"auth0").write `#{bin}/auth0 completion bash`
        (fish_completion/"auth0.fish").write `#{bin}/auth0 completion fish`
        (zsh_completion/"_auth0").write `#{bin}/auth0 completion zsh`
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/auth0/auth0-cli/releases/download/v1.33.0-beta.0/auth0-cli_1.33.0-beta.0_Linux_x86_64.tar.gz"
        sha256 "5ffd5f3fee109dbc45942c669216bfbf4a335044fcfd499ce87b449b1fe794c5"

        def install
          bin.install "auth0"

          (bash_completion/"auth0").write `#{bin}/auth0 completion bash`
          (fish_completion/"auth0.fish").write `#{bin}/auth0 completion fish`
          (zsh_completion/"_auth0").write `#{bin}/auth0 completion zsh`
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/auth0/auth0-cli/releases/download/v1.33.0-beta.0/auth0-cli_1.33.0-beta.0_Linux_arm64.tar.gz"
        sha256 "ccaa3905e228cd628ca6e9f2aad9be42ee8003b4127a9478329b594801fbb0d4"

        def install
          bin.install "auth0"

          (bash_completion/"auth0").write `#{bin}/auth0 completion bash`
          (fish_completion/"auth0.fish").write `#{bin}/auth0 completion fish`
          (zsh_completion/"_auth0").write `#{bin}/auth0 completion zsh`
        end
      end
    end
  end

  def caveats
    <<~EOS
      Thanks for installing the Auth0 CLI
    EOS
  end
end
