# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Auth0 < Formula
  desc "Build, manage and test your Auth0 integrations from the command line"
  homepage "https://auth0.github.io/auth0-cli"
  version "1.17.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/auth0/auth0-cli/releases/download/v1.17.1/auth0-cli_1.17.1_Darwin_x86_64.tar.gz"
      sha256 "faf71c7965e8d253caf4ca916c6673042db715f6444c57d6c74f5168048f0b51"

      def install
        bin.install "auth0"

        (bash_completion/"auth0").write `#{bin}/auth0 completion bash`
        (fish_completion/"auth0.fish").write `#{bin}/auth0 completion fish`
        (zsh_completion/"_auth0").write `#{bin}/auth0 completion zsh`
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/auth0/auth0-cli/releases/download/v1.17.1/auth0-cli_1.17.1_Darwin_arm64.tar.gz"
      sha256 "86319b4dfd2208325f2907e792eb2b66cb168286bea07ab7ba48cb5c38ddea17"

      def install
        bin.install "auth0"

        (bash_completion/"auth0").write `#{bin}/auth0 completion bash`
        (fish_completion/"auth0.fish").write `#{bin}/auth0 completion fish`
        (zsh_completion/"_auth0").write `#{bin}/auth0 completion zsh`
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/auth0/auth0-cli/releases/download/v1.17.1/auth0-cli_1.17.1_Linux_x86_64.tar.gz"
        sha256 "b9ad5c35de82fb283a0e0467bb1d6082572fdebce7d237c9f75d292f6a22d375"

        def install
          bin.install "auth0"

          (bash_completion/"auth0").write `#{bin}/auth0 completion bash`
          (fish_completion/"auth0.fish").write `#{bin}/auth0 completion fish`
          (zsh_completion/"_auth0").write `#{bin}/auth0 completion zsh`
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/auth0/auth0-cli/releases/download/v1.17.1/auth0-cli_1.17.1_Linux_arm64.tar.gz"
        sha256 "9959308bf9dbbb39420cb1d3a1a92c07f76b195df52fc553d534061f4027f714"

        def install
          bin.install "auth0"

          (bash_completion/"auth0").write `#{bin}/auth0 completion bash`
          (fish_completion/"auth0.fish").write `#{bin}/auth0 completion fish`
          (zsh_completion/"_auth0").write `#{bin}/auth0 completion zsh`
        end
      end
    end
  end

  def caveats
    <<~EOS
      Thanks for installing the Auth0 CLI
    EOS
  end
end
