# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Auth0 < Formula
  desc "Build, manage and test your Auth0 integrations from the command line"
  homepage "https://auth0.github.io/auth0-cli"
  version "1.19.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/auth0/auth0-cli/releases/download/v1.19.0/auth0-cli_1.19.0_Darwin_x86_64.tar.gz"
      sha256 "532672b36a40d17292ae2d60b43e954b3d4bbee02bdd80f13ddd2bf9aebb7d66"

      def install
        bin.install "auth0"

        (bash_completion/"auth0").write `#{bin}/auth0 completion bash`
        (fish_completion/"auth0.fish").write `#{bin}/auth0 completion fish`
        (zsh_completion/"_auth0").write `#{bin}/auth0 completion zsh`
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/auth0/auth0-cli/releases/download/v1.19.0/auth0-cli_1.19.0_Darwin_arm64.tar.gz"
      sha256 "133d3a680b984f19cf9601c5951ef85d9956d6a4c3de551fb7ef7314c4bfe830"

      def install
        bin.install "auth0"

        (bash_completion/"auth0").write `#{bin}/auth0 completion bash`
        (fish_completion/"auth0.fish").write `#{bin}/auth0 completion fish`
        (zsh_completion/"_auth0").write `#{bin}/auth0 completion zsh`
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/auth0/auth0-cli/releases/download/v1.19.0/auth0-cli_1.19.0_Linux_x86_64.tar.gz"
        sha256 "4a95958e7d269e0a66602c5f34d3ab7759344438dfdeb14c38837b2bb002f008"

        def install
          bin.install "auth0"

          (bash_completion/"auth0").write `#{bin}/auth0 completion bash`
          (fish_completion/"auth0.fish").write `#{bin}/auth0 completion fish`
          (zsh_completion/"_auth0").write `#{bin}/auth0 completion zsh`
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/auth0/auth0-cli/releases/download/v1.19.0/auth0-cli_1.19.0_Linux_arm64.tar.gz"
        sha256 "8773e67b52a5278bef51cff0f445e7615cf3e0e906d93a7416408b91cd6cb7d1"

        def install
          bin.install "auth0"

          (bash_completion/"auth0").write `#{bin}/auth0 completion bash`
          (fish_completion/"auth0.fish").write `#{bin}/auth0 completion fish`
          (zsh_completion/"_auth0").write `#{bin}/auth0 completion zsh`
        end
      end
    end
  end

  def caveats
    <<~EOS
      Thanks for installing the Auth0 CLI
    EOS
  end
end
