# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Auth0Beta < Formula
  desc "Build, manage and test your Auth0 integrations from the command line"
  homepage "https://auth0.github.io/auth0-cli"
  version "1.33.0-beta.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/auth0/auth0-cli/releases/download/v1.33.0-beta.1/auth0-cli_1.33.0-beta.1_Darwin_x86_64.tar.gz"
      sha256 "3f65da9dfdae9eecf5c5cc68f6e71098e41ffd99db5cfe1b48c3d7ba5916dca6"

      def install
        bin.install "auth0"

        (bash_completion/"auth0").write `#{bin}/auth0 completion bash`
        (fish_completion/"auth0.fish").write `#{bin}/auth0 completion fish`
        (zsh_completion/"_auth0").write `#{bin}/auth0 completion zsh`
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/auth0/auth0-cli/releases/download/v1.33.0-beta.1/auth0-cli_1.33.0-beta.1_Darwin_arm64.tar.gz"
      sha256 "fdbdf73cb5dc9c88f50f66e43497b73d6893941e4ea076f16a0df550048f17de"

      def install
        bin.install "auth0"

        (bash_completion/"auth0").write `#{bin}/auth0 completion bash`
        (fish_completion/"auth0.fish").write `#{bin}/auth0 completion fish`
        (zsh_completion/"_auth0").write `#{bin}/auth0 completion zsh`
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/auth0/auth0-cli/releases/download/v1.33.0-beta.1/auth0-cli_1.33.0-beta.1_Linux_x86_64.tar.gz"
        sha256 "696b0f931cf0b93bb34d85c04e8e38aa46973d7c1c04efcfc26fe07e0dc578d9"

        def install
          bin.install "auth0"

          (bash_completion/"auth0").write `#{bin}/auth0 completion bash`
          (fish_completion/"auth0.fish").write `#{bin}/auth0 completion fish`
          (zsh_completion/"_auth0").write `#{bin}/auth0 completion zsh`
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/auth0/auth0-cli/releases/download/v1.33.0-beta.1/auth0-cli_1.33.0-beta.1_Linux_arm64.tar.gz"
        sha256 "96e061762885621150a9d391b9e022c6314e7dfebbdc71c2261bdc536d35e15c"

        def install
          bin.install "auth0"

          (bash_completion/"auth0").write `#{bin}/auth0 completion bash`
          (fish_completion/"auth0.fish").write `#{bin}/auth0 completion fish`
          (zsh_completion/"_auth0").write `#{bin}/auth0 completion zsh`
        end
      end
    end
  end

  def caveats
    <<~EOS
      Thanks for installing the Auth0 CLI
    EOS
  end
end
